In [1]:

import torch
import torch.nn as nn
from tqdm import tqdm
import datetime
import wandb
import os
import numpy as np
import random
from sklearn.model_selection import train_test_split
import pandas as pd


from datasets.deepfake_ecg.Deepfake_ECG_Dataset import Deepfake_ECG_Dataset
from datasets.deepfake_ecg.Deepfake_ECG_Dataset import HR_PARAMETER
from datasets.deepfake_ecg.Deepfake_ECG_Dataset import QRS_PARAMETER
from datasets.deepfake_ecg.Deepfake_ECG_Dataset import PR_PARAMETER
from datasets.deepfake_ecg.Deepfake_ECG_Dataset import QT_PARAMETER
import utils.current_server as current_server



parameters = [HR_PARAMETER,QRS_PARAMETER,PR_PARAMETER,QT_PARAMETER]




device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

for parameter in parameters:
    # Create the dataset class
    dataset = Deepfake_ECG_Dataset(parameter=parameter)
    
 
    
    print('Parameter:', parameter)
    print('Length of Dataset:', len(dataset))
    print()

    null_count = 0
    for data in dataset:
        tensor_data = data[1]
        print(tensor_data)
        # Check for NaN or null values
        if torch.isnan(tensor_data).any() or tensor_data is None:
            null_count += 1

print("Null Values Count:", null_count)





Running limited dataset
Not running in ampere. Loading data from disk
loading ground truth labels
loaded ground truth labels
Parameter: hr
Length of Dataset: 999

tensor([59.6421])
tensor([65.3595])
tensor([61.0998])
tensor([69.7674])
tensor([62.3701])
tensor([63.5593])
tensor([66.3717])
tensor([66.9643])
tensor([76.5306])
tensor([66.3717])
tensor([68.8073])
tensor([71.0900])
tensor([63.0252])
tensor([67.1141])
tensor([84.7458])
tensor([67.8733])
tensor([73.5294])
tensor([62.3701])
tensor([64.1026])
tensor([64.9351])
tensor([80.])
tensor([61.4754])
tensor([78.7402])
tensor([70.9220])
tensor([70.9220])
tensor([70.2576])
tensor([65.3595])
tensor([75.9494])
tensor([78.1250])
tensor([68.9655])
tensor([88.7574])
tensor([76.5306])
tensor([71.2589])
tensor([68.3371])
tensor([74.0741])
tensor([65.2174])
tensor([62.7615])
tensor([70.2576])
tensor([65.7895])
tensor([67.8733])
tensor([76.7263])
tensor([65.3595])
tensor([68.0272])
tensor([80.2139])
tensor([71.9425])
tensor([69.6056])
tensor([70.92

In [10]:
null_count = 0
for data in dataset:
    tensor_data = data[1]
    print(tensor_data)
    # Check for NaN or null values
    if torch.isnan(tensor_data).any() or tensor_data is None:
        null_count += 1

print("Null Values Count:", null_count)

tensor([434.])
tensor([404.])
tensor([416.])
tensor([390.])
tensor([366.])
tensor([408.])
tensor([354.])
tensor([402.])
tensor([380.])
tensor([420.])
tensor([406.])
tensor([390.])
tensor([434.])
tensor([380.])
tensor([362.])
tensor([424.])
tensor([386.])
tensor([384.])
tensor([396.])
tensor([388.])
tensor([386.])
tensor([422.])
tensor([388.])
tensor([406.])
tensor([386.])
tensor([390.])
tensor([426.])
tensor([390.])
tensor([386.])
tensor([394.])
tensor([384.])
tensor([386.])
tensor([414.])
tensor([410.])
tensor([346.])
tensor([392.])
tensor([428.])
tensor([390.])
tensor([382.])
tensor([390.])
tensor([404.])
tensor([398.])
tensor([382.])
tensor([400.])
tensor([370.])
tensor([392.])
tensor([360.])
tensor([414.])
tensor([378.])
tensor([386.])
tensor([396.])
tensor([388.])
tensor([406.])
tensor([394.])
tensor([404.])
tensor([406.])
tensor([408.])
tensor([428.])
tensor([414.])
tensor([398.])
tensor([398.])
tensor([390.])
tensor([372.])
tensor([390.])
tensor([386.])
tensor([390.])
tensor([37